image: alexkuc/docker:gitlab-shared-runner
services:
  - docker:dind

stages:
  - test

cache:
  key:
    files:
      - test/composer.lock
      - test/composer.json
  paths:
    - test/vendor/

tests:
  stage: test
  timeout: 5m

  script:
    - scripts/host/up.sh
    - scripts/code/setup.sh
    - scripts/code/test.sh

  variables:
    # prevent health check errors
    # https://gitlab.com/gitlab-org/gitlab-foss/issues/64775
    SERVICE_PORT_2376_TCP_PORT: 2375

  artifacts:
    paths:
      - test/tests/_output/
    when: on_failure
    expire_in: 1 week
