version: 2.1
jobs:
  linters:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: Lint (ShellCheck)
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  assets:
    docker:
      - image: alpine
    steps:
      - run:
          name: Compile assets
          command: |
            # see the article below on how to pass data between
            # "Persisting Data in Workflows: When to Use Caching, Artifacts, and Workspaces"
            # https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/
            echo ''
            echo 'Placeholder step for compiling assets'
            echo 'Either complete this step or remove it entirely'
            echo ''
  tests:
    machine:
      image: ubuntu-1604:201903-01
      # docker_layer_caching: true (requires paid subscription)    # default - false
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "wp-browser/composer.json" }}-{{ checksum "wp-browser/composer.lock" }}
      - run:
          name: Run CI tests
          no_output_timeout: 5m
          command: |
            host-scripts/up.sh
            host-scripts/composer.sh
            .circleci/fix-permissions.sh
            host-scripts/test.sh
      - save_cache:
          key: composer-{{ checksum "wp-browser/composer.json" }}-{{ checksum "wp-browser/composer.lock" }}
          paths:
              - "wp-browser/vendor/"
          when: on_success
      - store_artifacts:
          path: "wp-browser/tests/_output/"

  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Deploy
          when: on_success
          command: |
            # See the following page with deploy examples
            # https://circleci.com/docs/2.0/deployment-integrations/
            echo ''
            echo 'Placeholder step for deployment'
            echo 'Either complete this step or remove it entirely'
            echo ''

workflows:
  version: 2
  workflow_1:
    jobs:
      - linters
      - tests:
          requires:
            - linters
      - assets:
          requires:
            - linters
      - deploy:
          requires:
            - assets
            - tests
